### ISSUE TITLE
Your Snippet has the same namespace as the Google Analytics Dashboard Widget

### ISSUE THREAD

**Issue by gadgetto** [yogoo/Analytics#1]
Your Analytics snippet has the same namespace "Analytics" as the Google Analytics Dashboard Widget.

**Comment by yogoo** [comment]
Good catch! I contacted the author of Google Analytics Dashboard Widget to find a resolution. Updates will be posted here.

In the meantime, if you want to use them side by side, you can get the source of Analytics and install the snippet and chunk manually.

**Comment by yogoo** [comment]
The developer of Google Analytics Dashboard Widget doesn't return my emails.

Strictly speaking he's using a non-conventional namespace naming pattern (ie, Analytics). I don't want to fix this by picking up a random namespace which would be irrelevant to the plugin name and which might collide with another plug-in. On a large scale this would only make it unmanageable for developers to publish a modx extra.

Kindly file a bug report with him and ask him to switch to a namespace that fits his plugin name.

**Comment by gadgetto** [comment]
I already tried to contact him via email and Twitter but also no response.

**Comment by yogoo** [comment]
Well, let's hope he'll keep it in mind when updating his extra.

I'm closing the ticket as it's an issue with Google Analytics Dashboard Widget and not with Analytics.
