### ISSUE TITLE
Invalid JS in ga option

### ISSUE THREAD

**Issue by wallacio** [yogoo/Analytics#11]
Closing curly bracket should be regular bracket in
analytics.class.php(179):

if ($this->config['enhancedLinkAttribution']) $UAtracker.= "ga('require','linkid','linkid.js'};";

should be
if ($this->config['enhancedLinkAttribution']) $UAtracker.= "ga('require','linkid','linkid.js');";

**Comment by yogoo** [comment]
good catch! It's fixed in v2.0.1-pl [availble from the download manager]. Thanks for reporting it.
