### ISSUE TITLE
little mistake on docs http://rtfm.modx.com/display/ADDON/Analytics

### ISSUE THREAD

**Issue by jiripavlicek** [yogoo/Analytics#2]
Hi Jérôme, good work!

Please add to docs some like this:

Analytics snippet must be inserted non-cashed, because if page is first time generated (and cashed) by manager-logged user, in cache is stored empty snippet content. And the analogic for first time non-loffed visitor.

Jiri Pavlicek
jiri@pavlicek.cz

**Comment by yogoo** [comment]
Hi Jiri,

Good catch! I forgot to mention the snippet must be called uncached. The doc is updated.
Thanks for pointing it out !
