### ISSUE TITLE
Hide Settings Tab in Dashboard Widget

### ISSUE THREAD

**Issue by brianlarson** [yogoo/Analytics#3]
First off, great Add-On! I love the dashboard widget. I hope this is the right place to put a feature request (as it's not an "issue"). Would like for a way to hide the Settings tab in the dashboard widget so clients cannot view data for other accounts attached to the Google ID (on the dashboard widget: Settings > Site profile:). I noticed "Ability to hide tabs" in changelog.txt but couldn't figure out how. Perhaps just a new System setting to show or hide it? Again, awesome work! Thanks for your consideration and... viva la MODX!

**Comment by brianlarson** [comment]
Nevermind. I'm an idiot. I figured out that you can add "settings":false in System Settings under analytics_activetabs. Oops! Hopefully this helps someone else that runs across this. I guess one suggestion for yogoo would be to have it set to true by default as I had to add it. Thanks!

**Comment by yogoo** [comment]
Brian, thanks for the feedback. Here is indeed the place to ask for new features. However what you describe is _not_ part of Analytics.

What you describe sounds like the [Google Analytics Dashboard Widget](http://modx.com/extras/package/googleanalyticsdashboardwidget) extra. The confusion might come from the fact that this extra uses a non-standard namespace and appears as simply "Analytics" in the manager. See issue #1 for more on this.

The details to contact the developer are available from [Google Analytics Dashboard Widget description](http://modx.com/extras/package/googleanalyticsdashboardwidget). Hope this helps.

**Comment by brianlarson** [comment]
Ooops! My mistake. I am using both add-ons. Great work on your's as well! Thanks so much for setting me straight, yogoo.
