### ISSUE TITLE
Unable to get stats from analytics 

### ISSUE THREAD

**Issue by AmaZili** [yogoo/Analytics#6]
Hi Jérome,

I was trying to implement Analytics on my modx revo environment Rev 2.2.7pl site, and I can't get it to send stats to google (watching site analytics in real time mode)

I provide you under with the snippet call and my original ga code : 

[[!Analytics? &setAccount=`UA-35841363-1` &setDomainName=`amazili-communication.com` &debug=`1`]]

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-35841363-1']);
  _gaq.push(['_setDomainName', 'amazili-communication.com']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

the debug code is hereunder : 

<script>
var _gaq=_gaq||[];
var pluginUrl='//www.google-analytics.com/plugins/ga/inpage_linkid.js';
_gaq.push=[ ['_require', 'inpage_linkid', pluginUrl],['_setAccount','UA-35841363-1'], ['_trackPageview'], ['_setDomainName', 'amazili-communication.com'] ];
(function(d,t)
{var g=d.createElement(t),
s=d.getElementsByTagName(t)[0];
g.async=1;
g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
s.parentNode.insertBefore(g,s)}(document,'script'));</script>

here are the current installed packages, all in the latest version : 

Analytics
archivist
Articles
Big Brother
FormIt
getpage
getResourceField
getresources
Quip
sitemapFriend
taglister
Wayfinder

Any idea ?

Thanks

Philippe

**Comment by yogoo** [comment]
Have you enabled it? [See instructions at Google](https://support.google.com/analytics/answer/2558867?hl=en&topic=2558810&ctx=topic).

**Comment by govza** [comment]
Used <a href="https://github.com/yogoo/Analytics/blob/2bc0963289cb94093bc570c36f83960ce974ac49/chunks/googleAnalyticsTpl.html">old tpl file</a> to use analytics without Enhanced Link Attribution enabled. 
May be it would be better keep old tpl file and add another for Enhaced users?

**Comment by yogoo** [comment]
The old tpl file code should still work. Make sure the output code is valid as Modx will process and remove all square brackets around "+gaq_option" if the original white space are removed.

For Enhanced Link Attribution to work you need to enable it in your Google Analytics' dashboard. Without this activation, the "new" tracking code should work the "old" way.

btw, why would you want to disable Enhanced Link Attribution?

**Comment by yogoo** [comment]
closed as per [pull request 7](https://github.com/yogoo/Analytics/pull/7)
