### ISSUE TITLE
Universal Analytics

### ISSUE THREAD

**Issue by grinvladimir** [yogoo/Analytics#8]
Can you do an option for GA Universal?
Thanks

**Comment by yogoo** [comment]
Just to let you know that a version with Universal Analytics is ready. I still need to find the time to test it before it can be released to the public.

**Comment by grinvladimir** [comment]
Great news! Thanks. Waiting for a public beta

**Comment by yogoo** [comment]
Thanks for your cheerful comment! Woke up some energy to publish this (production ready):
https://github.com/yogoo/Analytics/blob/v2.x_dev/_packages/analytics-1.2.0-pl.transport.zip

Remember to delete it and install it from the modx repo once it's released to the public (in a few days).

**Comment by grinvladimir** [comment]
Awesome work.
Tomorrow I'll test it on live site.
Review is coming soon.

**Comment by yogoo** [comment]
Thanks! Let me know about the review!

Finished to polish it this morning. This updated transport package is the one that will go public:
https://github.com/yogoo/Analytics/blob/v2.x_dev/_packages/analytics-1.2.0-pl.transport.zip

**Comment by yogoo** [comment]
Implemented in v2.0.0-pl
