### ISSUE TITLE
change .google-analytics.com/ga.js to stats.g.doubleclick.net/dc.js

### ISSUE THREAD

**Issue by Lefthandmedia** [yogoo/Analytics#9]
Hi,
I got a request from a client to change these  lines in de GA code.

.google-analytics.com/ga.js to stats.g.doubleclick.net/dc.js

It's conform these guidelines by google https://support.google.com/analytics/answer/2444872.
is there a way to make that selectable via a system setting?

tnx
RDG

**Comment by yogoo** [comment]
This is not supported in the current version. You'll have to either change the url in the chunk or change the name of the chunk in the snippet to point to a custom chunk.

**Comment by yogoo** [comment]
Version 1.2.0 supports Display Advertising features. Set "displayfeatures" to yes (snippet property set).
https://github.com/yogoo/Analytics/blob/v2.x_dev/_packages/analytics-1.2.0-pl.transport.zip

Remember to delete it and install it from the modx repo once it's released to the public (in a few days).

**Comment by yogoo** [comment]
Implemented in v2.0.0-pl. Please note that system settings are not supported anymore in favor of prperties set.
